# https://taskfile.dev

version: "3"

tasks:
    default:
        desc: "Git overview"
        cmds:
            - "git status"

    publish:
        desc: "Commit all changes and push to remote with message"
        cmds:
            - "git add --all"
            - "git commit -m {{.CLI_ARGS}}"
            - "git push"
