# https://taskfile.dev

version: "3"

tasks:
    default:
        desc: "List tasks"
        cmd: task --list

    audit:
        desc: "Run Sourcery for all templates and watch for changes"
        cmds:
            - |
                sourcery \
                  --sources Targets/{{.CLI_ARGS}} \
                  --templates Audit/Templates \
                  --output Audit/Generated \
                  --prune \
                  --watch \
                  --verbose
